# .readthedocs.yaml

version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.9"

sphinx:
  configuration: docs/source/conf.py

formats:
  - pdf
  - epub

python:
  install:
    - method: pip
      path: .
  extra_requirements:
    - doc  # This will install the optional dependencies for documentation specified in pyproject.toml
