# .readthedocs.yaml

version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.9"

sphinx:
  configuration: docs/source/conf.py

formats:
  - pdf
  - epub

# python:
#   install:
#     - requirements: requirements.txt
#     - requirements: requirements_dev.txt
